/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IChainlinkVRFv2DirectFundingProxy,
  IChainlinkVRFv2DirectFundingProxyInterface,
} from "../../../contracts/ChainlinkVRFv2/IChainlinkVRFv2DirectFundingProxy";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "gasLeft",
        type: "uint256",
      },
    ],
    name: "ChainlinkVRFv2DirectFundingProxy_InsufficientGasForConsumer",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "requestId",
        type: "bytes32",
      },
    ],
    name: "ChainlinkVRFv2DirectFundingProxy_RequestAlreadyHandled",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "offendingAddress",
        type: "address",
      },
    ],
    name: "ChainlinkVRFv2DirectFundingProxy_UnauthorizedBackend",
    type: "error",
  },
  {
    inputs: [],
    name: "ChainlinkVRFv2DirectFundingProxy_ZeroAddress",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "dapp",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "nonce",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "bytes32",
        name: "requestId",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "_callbackGasLimit",
        type: "uint32",
      },
      {
        indexed: false,
        internalType: "uint16",
        name: "_requestConfirmations",
        type: "uint16",
      },
      {
        indexed: false,
        internalType: "uint32",
        name: "_numWords",
        type: "uint32",
      },
    ],
    name: "RandomnessRequest",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint8[]",
        name: "sigV",
        type: "uint8[]",
      },
      {
        internalType: "bytes32[]",
        name: "sigR",
        type: "bytes32[]",
      },
      {
        internalType: "bytes32[]",
        name: "sigS",
        type: "bytes32[]",
      },
      {
        internalType: "address",
        name: "requestOrigin",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "chainId",
        type: "uint256",
      },
      {
        internalType: "bytes32",
        name: "requestId",
        type: "bytes32",
      },
      {
        internalType: "uint256[]",
        name: "randomWords",
        type: "uint256[]",
      },
    ],
    name: "callbackWithRandomness",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "requestId",
        type: "bytes32",
      },
    ],
    name: "callingContracts",
    outputs: [
      {
        internalType: "address",
        name: "callingContract",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "requestId",
        type: "bytes32",
      },
    ],
    name: "requestHandled",
    outputs: [
      {
        internalType: "bool",
        name: "handled",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint32",
        name: "_callbackGasLimit",
        type: "uint32",
      },
      {
        internalType: "uint16",
        name: "_requestConfirmations",
        type: "uint16",
      },
      {
        internalType: "uint32",
        name: "_numWords",
        type: "uint32",
      },
    ],
    name: "requestRandomness",
    outputs: [
      {
        internalType: "bytes32",
        name: "requestId",
        type: "bytes32",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
] as const;

export class IChainlinkVRFv2DirectFundingProxy__factory {
  static readonly abi = _abi;
  static createInterface(): IChainlinkVRFv2DirectFundingProxyInterface {
    return new utils.Interface(
      _abi
    ) as IChainlinkVRFv2DirectFundingProxyInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IChainlinkVRFv2DirectFundingProxy {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IChainlinkVRFv2DirectFundingProxy;
  }
}
