/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IChainlinkVRFv2DirectFundingConsumer,
  IChainlinkVRFv2DirectFundingConsumerInterface,
} from "../../../contracts/ChainlinkVRFv2/IChainlinkVRFv2DirectFundingConsumer";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "needed",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "balance",
        type: "uint256",
      },
    ],
    name: "IChainlinkVRFv2DirectFundingConsumer_InsufficientERC20Balance",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "needed",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "provided",
        type: "uint256",
      },
    ],
    name: "IChainlinkVRFv2DirectFundingConsumer_NativeFeeIncorrect",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "unauthorizedProvider",
        type: "address",
      },
    ],
    name: "IChainlinkVRFv2DirectFundingConsumer_RandomnessProviderUnauthorized",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "operator",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "proxyContractAddress",
        type: "address",
      },
    ],
    name: "ProxyContractSet",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint8[]",
        name: "sigV",
        type: "uint8[]",
      },
      {
        internalType: "bytes32[]",
        name: "sigR",
        type: "bytes32[]",
      },
      {
        internalType: "bytes32[]",
        name: "sigS",
        type: "bytes32[]",
      },
      {
        internalType: "address",
        name: "requestOrigin",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "chainId",
        type: "uint256",
      },
      {
        internalType: "bytes32",
        name: "requestId",
        type: "bytes32",
      },
      {
        internalType: "uint256[]",
        name: "randomWords",
        type: "uint256[]",
      },
    ],
    name: "verifyAndFulfillRandomness",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IChainlinkVRFv2DirectFundingConsumer__factory {
  static readonly abi = _abi;
  static createInterface(): IChainlinkVRFv2DirectFundingConsumerInterface {
    return new utils.Interface(
      _abi
    ) as IChainlinkVRFv2DirectFundingConsumerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IChainlinkVRFv2DirectFundingConsumer {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IChainlinkVRFv2DirectFundingConsumer;
  }
}
